export const GET_USERS = "GET_USERS";
export const INITIATE_GET_USERS = "INITIATE_GET_USERS";
export const SELECT_USER = "SELECT_USER";
export const UPDATE_USER = "UPDATE_USER";
export const INITIATE_UPDATE_USER = "INITIATE_UPDATE_USER";

export const GET_HOBBIES_NAMES = "GET_HOBBIES_NAMES";
export const INITIATE_GET_HOBBIES_NAMES = "INITIATE_GET_HOBBIES_NAMES";
export const GET_USER_HOBBIES = "GET_USER_HOBBIES";
export const INITIATE_GET_USER_HOBBIES = "INITIATE_GET_USER_HOBBIES"
export const CREATE_HOBBY = "CREATE_HOBBY";
export const INITIATE_CREATE_HOBBY = "INITIATE_CREATE_HOBBY"
